<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Attendance Summary Report</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Great+Vibes&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="faculty-download_report.css">
</head>
<body class="report-body">

  <div class="report-paper document" id="printableArea">
    <div class="faculty-card">
      <div class="avatar">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
          <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
          <circle cx="12" cy="7" r="4"></circle>
        </svg>
      </div>

      <div class="faculty-info">
        <h1 id="facultyName">Loading...</h1>
        <div class="faculty-meta">
          <span id="college">College of Engineering</span>
          &nbsp; | &nbsp;
          <span id="course">Loading...</span>
        </div>

        <div class="faculty-details">
          <div class="detail-item">
            <span>UID:</span>
            <p id="uid">---</p>
          </div>
          <div class="detail-item">
            <span>Email:</span>
            <p id="email">---</p>
          </div>
        </div>
      </div>
    </div>

    <h2 class="table-title">Academic Year Attendance Summary</h2>

    <table class="attendance-table">
      <thead>
        <tr>
          <th>Category</th>
          <th>1<sup>st</sup> Sem</th>
          <th>2<sup>nd</sup> Sem</th>
          <th>3<sup>rd</sup> Sem</th>
          <th class="total-col">TOTAL</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>School Days</th>
          <td id="school1">0</td>
          <td id="school2">0</td>
          <td id="school3">0</td>
          <td id="schoolTotal" class="total">0</td>
        </tr>
        <tr>
          <th>Days Present</th>
          <td id="present1">0</td>
          <td id="present2">0</td>
          <td id="present3">0</td>
          <td id="presentTotal" class="total">0</td>
        </tr>
        <tr>
          <th>Days Absent</th>
          <td id="absent1">0</td>
          <td id="absent2">0</td>
          <td id="absent3">0</td>
          <td id="absentTotal" class="total">0</td>
        </tr>
      </tbody>
    </table>

    <div class="footer-btn-container">
      <button class="download-btn" onclick="window.print()">Download as PDF</button>
    </div>

    <div class="report-footer">
      <p>Generated by Astraea Academy Systems • 2026</p>
    </div>
  </div>

  <script src="faculty-download_report.js"></script>
</body>
</html>